routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use IEXBase\TronAPI\Tron;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|اینجا وقتیی که کاربر رفته باشه داخل پنلش میتونه دسترسی داشته باشه
روت های لاگین داخل فایل web.php موجود میباشد
*/
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
Route::post('users/{user}/block-unblock','UsersController@block_unblock')->name('users.block_unblock');
Route::resource('users','UsersController');
Route::get('users/{user}/login-panel', 'UsersController@login_panel')->name('users.login-panel');
Route::resource('invest_shares','Invest_SharesController');
Route::post('invest_shares/profits','Invest_SharesController@inviter_profit_store')->name('invest_shares.inviter_profit.store');
Route::post('invest_shares/cancel-invest','Invest_SharesController@cancel_invest')->name('invest_shares.cancel_invest');
Route::resource('ctr','CtrController')->only(['index','store']);
Route::post('ctr/profits','CtrController@inviter_profit_store')->name('ctr.inviter_profit.store');

Route::get('settings','SettingsController@general')->name('settings.general');
Route::get('settings/withdraws','SettingsController@withdraw')->name('settings.withdraws');
Route::post('settings','SettingsController@update')->name('settings.general.store');
Route::post('settings/currency','SettingsController@currency_update')->name('settings.currency.store');
Route::get('/profile', 'ProfileController@profile')->name('profile');
Route::put('/profile/{user}', 'ProfileController@update_profile')->name('profile.update');
Route::put('/change-password/{user}', 'ProfileController@change_pass')->name('change-password');
Route::get('reports','ReportController@index')->name('reports.index');
Route::resource('notifications','NotificationController');
Route::get('get-user','NotificationController@users')->name('notifications.get_user');
Route::get('get-amount','UsersController@get_amount')->name('get_amount');
Route::post('users/change_wallet','UsersController@change_wallet')->name('users.change_wallet');
Route::post('settings/message','SettingsController@message')->name('settings.message.update');
Route::get('ticket', "TicketsController@index")->name('ticket.index');
Route::get('ticket/create', "TicketsController@create")->name('ticket.create');
Route::get('ticket/{code}/show', "TicketsController@show")->name('ticket.show');
Route::post('ticket/close', "TicketsController@close")->name('ticket.close');
Route::post('ticket/{code}/update', "TicketsController@update")->name('ticket.update');

routes/web.php
<?php

use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use IEXBase\TronAPI\Tron;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', "App\Http\Controllers\User\HomeController@home");
Route::get('/file/{guard}/{id}/{file}',
    function ($guard, $id, $file) {
        $path = storage_path('app/public/tickets/' . $guard . '/' . $id . '/' . $file);
        if (!File::exists($path)) {
            abort(404);
        }
        $file = File::get($path);
        $type = File::mimeType($path);
        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);
        return $response;
    })->name('file.ticket.view');

Route::post('convert-to-parameter-save', function (\Illuminate\Http\Request $request) {
    $model = \App\Models\TransactionTron::find($request->id);
    $model->ethers_data = $request->address;
    $model->save();
    return 1;
})->name('convert-to-parameter-save');

// روت هایی برای ورود ادمین
Route::middleware('guest.admin')
    ->prefix('admin')
    ->name('admin.')
    ->namespace('App\Http\Controllers\Admin\Auth')
    ->group(function () {
        Route::get('login', 'LoginController@loginForm')->name('login.form');
        Route::post('login', 'LoginController@login')->name('login');
    });

Route::middleware('guest')->namespace('App\Http\Controllers\User\Auth')->group(function () {
    Route::get('register', 'RegisterController@register')->name('register.form');
    Route::post('register/store', 'RegisterController@store')->name('register.store');
    Route::get('register/{code?}', 'RegisterController@show_registration_form')->name('register');
    Route::get('email/verify/{token}', 'RegisterController@verifyEmail')->name('register.verify.email');
    Route::get('forget/password', 'ForgetPasswordController@forget')->name('forget.form');
    Route::post('forget/send-email', 'ForgetPasswordController@sendEmail')->name('forget.send-email');
    Route::get('forget/verify/{token}', 'ForgetPasswordController@verifyToken')->name('forget.verify-token');
    Route::post('forget/new-password', 'ForgetPasswordController@newPassword')->name('forget.new-password');
    Route::get('login', 'LoginController@loginForm')->name('login.form');
    Route::post('login/user', 'LoginController@login')->name('login.login');
    Route::get('login/step', 'LoginController@login_step_form')->name('login.step.form');
    Route::post('login/step/user', 'LoginController@login_step')->name('login.step')->middleware('2fa.login');
});

// روت های مربوط به کاربر که داخل پنل کاربری لاگین شده
Route::middleware('auth')->namespace('App\Http\Controllers\User')->group(function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('user.dashboard');
    Route::get('settings', 'SettingController@general')->name('user.settings');

    Route::get('invest/cancel/{invest_shares}', 'Invest_SharesController@cancel')->name('user.invest.cancel');
    Route::get('invest/add-to-share/{invest_shares}', 'Invest_SharesController@add_to_share')->name('user.invest.add_to_share');
    Route::get('invest/{invest_shares}/logs', 'Invest_SharesController@logs')->name('user.invest.logs');
    Route::get('shares/{invest_shares}/logs', 'Invest_SharesController@logs')->name('user.shares.logs');
    Route::resource('invest', 'Invest_SharesController', ['as' => 'user']);
    Route::resource('shares', 'Invest_SharesController', ['as' => 'user']);
    Route::get('buy-ctr', 'AssetsController@buy_ctr_view')->name('user.buy-ctr');
    Route::post('buy-ctr', 'AssetsController@buy_ctr_store')->name('user.buy-ctr.store');

    Route::post('register_authenticator', 'SettingController@register_authenticator')->name('user.register_authenticator');
    Route::post('deactivate_authenticator', 'SettingController@deactivate_authenticator')->name('user.deactivate_authenticator');
    Route::post('login_2fa', 'SettingController@login_2fa')->name('user.login_2fa');
    Route::get('logout', 'Auth\LoginController@logout')->name('user.logout');
    Route::get('notifications', 'NotificationController@index')->name('notification.index');
    Route::get('notification/{id}', 'NotificationController@show')->name('notification.show');

    Route::post('assets/{asset_unit}/price-on-usdt', 'AssetsController@price_on_usdt')->name('assets.price_on_usdt');
    Route::post('assets/{asset_unit}/convert-to-usdt', 'AssetsController@convert_to_usdt')->name('assets.convert_to_usdt');

    Route::get('assets', 'AssetsController@index')->name('assets');
    Route::post('assets/get-address-wallet', 'AssetsController@getAddressWallet')->name('assets.get-address-wallet');
    Route::post('assets/get-amount-wallet', 'AssetsController@getAmountWallet')->name('assets.get-amount-wallet');
    Route::post('assets/withdrawal-fee', 'AssetsController@WithdrawalFee')->name('assets.wallet.withdrawal-fee');
    Route::post('assets/withdraw', 'AssetsController@withdraw')->name('assets.withdraw.store')->middleware(['auth', '2fa']);
    Route::post('assets/security-withdraw', 'AssetsController@security_withdraw')->name('assets.withdraw.security');
    Route::post('withdraw', 'AssetsController@withdraw')->name('withdraw.store')->middleware(['auth', '2fa']);
    Route::get('withdraw-report', 'TransactionController@withdraw_report_form')->name('withdraw-report');
    Route::get('/profile', 'DashboardController@profile')->name('profile');
    Route::put('/profile/{user}', 'DashboardController@update_profile')->name('profile.update');
    Route::put('/change-password/{user}', 'DashboardController@change_pass')->name('change-password');
    Route::get('ticket', "TicketController@index")->name('ticket.index');
    Route::get('ticket/create', "TicketController@create")->name('ticket.create');
    Route::get('ticket/{code}/show', "TicketController@show")->name('ticket.show');
    Route::post('ticket/store', "TicketController@store")->name('ticket.store');
    Route::post('ticket/{code}/update', "TicketController@update")->name('ticket.update');
});

app/Models/Notification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    use HasFactory;

    protected $fillable=[
        'user_id',
        'title',
        'description',
        'color',
        'icon',
        'started_at',
        'view',
    ];
    public function viewNotification()
    {
        return $this->hasOne(NotificationView::class,'notification_id');
    }
}

app/Models/NotificationView.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class NotificationView extends Model
{
    use HasFactory;

    protected $fillable = [
        'notification_id',
        'user_id',
    ];

    public function notification()
    {
        return $this->belongsTo(Notification::class, 'notification_id');
    }
}

app/Http/Controllers/Admin/NotificationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Notification;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class NotificationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notifications = Notification::orderBy('id','desc')->paginate(5);
        return view('admin.notifications.index', compact('notifications'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        return view('admin.notifications.create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'color' => 'required',
            'icon' => 'required',
            'description' => 'required',
            'user_id' => 'required_if:receiver,1',
        ]);

        $started_at = $request['started_at'] && !empty($request['started_at']) ? $started_at = Carbon::parse($request['started_at']) : $started_at = Carbon::now();
        try {
            Notification::create([
                'user_id' => ($request['user_id'])?$request['user_id']:0,
                'title' => $request['title'],
                'description' => $request['description'],
                'color' => $request['color'],
                'icon' => $request['icon'],
                'started_at' => $started_at,
            ]);

            return response()->json(['status' => 100, 'msg' => 'پیغام با موفقیت ذخیره شدند']);
        } catch (\Exception $exception) {
            return response()->json(['status' => 500, 'msg' => 'خطایی رخ داده است. لطفا بعدا امتحان کنید.']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $notification = Notification::select([
            '*',
            'user'=>User::select([DB::raw("concat(email,' ','(',code,')') as email")])->whereColumn('Notifications.user_id','users.id')->limit(1)
        ])->findOrFail($id);
        return view('admin.notifications.edit', compact('notification'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
            'color' => 'required',
            'icon' => 'required',
            'description' => 'required',
            'user_id' => 'required_if:receiver,1',
        ]);

        $started_at = $request['started_at'] && !empty($request['started_at']) ? $started_at = Carbon::parse($request['started_at']) : $started_at = Carbon::now();
        try {
            $notification = Notification::query()->findOrFail($id);
            $notification->update([
                'user_id' => ($request['user_id'])?$request['user_id']:0,
                'title' => $request['title'],
                'description' => $request['description'],
                'color' => $request['color'],
                'icon' => $request['icon'],
                'started_at' => $started_at,
            ]);

            return response()->json(['status' => 100, 'msg' => 'پیغام با موفقیت ویرایش شد.']);
        } catch (\Exception $exception) {
            return response()->json(['status' => 500, 'msg' => 'خطایی رخ داده است.لطفا بعدا امتحان کنید.']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function users(Request $request)
    {
        try {
            $users = User::select(['id', DB::raw("concat(email,' ','(',code,')') as email")])
                ->where('code', 'LIKE', '%' . $request['term'] . '%')
                ->orwhere('email', 'LIKE', '%' . $request['term'] . '%')
                ->get()->toArray();

            return response()->json($users);
        } catch (\Exception $exception) {
            return response()->json($exception);
        }


    }
}

app/Http/Controllers/User/NotificationController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Notification;
use App\Models\NotificationView;
use Carbon\Carbon;
use Illuminate\Http\Request;

class NotificationController extends Controller
{
    public function index()
    {
        $user = auth('web')->user();
        $notifications = Notification::with('viewNotification')
            ->where('user_id', $user->id)
            ->where('started_at', '<=', Carbon::now())
            ->orWhere('user_id', 0)
            ->where('started_at', '<=', Carbon::now())
            ->orderBy('id', 'desc')->paginate(10);
        return view('user.notification.index', compact('notifications'));
    }

    public function show($id)
    {
        $id = base64_decode($id);
        $user = auth('web')->user();
        $notification = Notification::with('viewNotification')
            ->where('id', $id)
            ->where('user_id', $user->id)
            ->where('started_at', '<=', Carbon::now())
            ->orWhere('user_id', 0)->where('id', $id)
            ->where('started_at', '<=', Carbon::now())
            ->firstOrFail();
        if (!$notification->viewNotification) {
            try {
                $this->updateView($notification, $user);
            } catch (\Exception $e) {
                return redirect()->route('notification.index');
            }
        }
        return view('user.notification.show', compact('notification'));
    }

    private function updateView($data, $user)
    {
        $notification = $data;
        $notification->view = 1;
        $notification->save();
        NotificationView::firstOrCreate([
            'notification_id' => $data->id,
        ], [
            'notification_id' => $data->id,
            'user_id' => $user->id
        ]);
    }
}

resources/views/admin/notifications/create.blade.php
@extends('templates.admin.master_page')
@section('title_browser')
    ایجاد پیغام
@endsection
@section('style')
    <style>
        button {
            overflow: hidden !important;
        }
        #ckeditor{
            display: none;
        }
    </style>
@endsection
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="row align-items-center">
                    <div class="col-md-8">
                        <h3 class="page-title m-0">ایجاد پیغام </h3>
                    </div>
                    <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end page-title-box -->
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('admin.notifications.store')}}" method="post">
                        @csrf
                        <div class="row justify-content-center">
                            <div class="form-group col-lg-10 col-md-4 col-sm-6">
                                <label for="example-text-input" class="">عنوان</label>
                                <input type="text" name="title" class="form-control">
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div class="form-group col-lg-10 col-md-4 col-sm-6">
                                <label for="example-text-input" class="">توضیحات</label>
                                <textarea id="ckeditor" name="description" rows="10" cols="125">
            </textarea>
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div class="form-group col-lg-2 col-md-3 col-sm-6 mt-3">
                                <div class="form-check">
                                    <input class="receiver" type="radio" name="receiver" id="exampleRadios1" value="0" checked>
                                    <label class="form-check-label" for="exampleRadios1">
                                        همه کاربران
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="receiver" type="radio" name="receiver" id="exampleRadios2" value="1">
                                    <label class="form-check-label" for="exampleRadios2">
                                        کاربر خاص
                                    </label>
                                </div>

                            </div>
                            <div class="form-group col-lg-3 col-md-4 col-sm-6 d-none">
                                <label for="example-text-input" class="">کاربران</label>
                                <select id="users" type="text" name="user_id" class="form-control users">
                                    <option value="">انتخاب کنید...</option>
                                </select>
                            </div>
                            <div class="form-group col-lg-2 col-md-4 col-sm-6">
                                <label for="example-text-input">رنگ پیغام</label>
                                <select name="color" class="form-control">
                                    <option value="info">info</option>
                                    <option value="warning">warning</option>
                                    <option value="danger">danger</option>
                                </select>
                            </div>
                            <div class="form-group col-lg-4 col-md-4 col-sm-6">
                                <label for="example-text-input" readonly>تاریخ</label>
                                <sub class="text-danger">درصورت تمایل به ارسال در زمان حاضر این فیلد را پر نکنید.</sub>
                                <input name="started_at" class="form-control datePicker" readonly>
                            </div>
                            <div class="form-group col-lg-1 col-md-4 col-sm-6">
                                <label for="example-text-input">آیکون</label>
                                <span class="input-group-prepend">
            <button name="icon" class="btn btn-danger" data-icon="" role="iconpicker"></button>
        </span>

                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <button type="submit" class="btn btn-info btn-lg ajaxStore">ایجاد پیغام</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $(document).on('change','.receiver',function (){
                var val=$(this).val();
                var elem=$(".users").closest(".form-group");
                if (val==1) {
                    elem.removeClass('d-none');
                }else {
                    elem.addClass('d-none');
                }
            })
            $('.users').select2({
                width: '100%',
                minimumInputLength: 3,
                ajax: {
                    url: `{{ route('admin.notifications.get_user') }}`,
                    dataType: 'json',
                    type: "get",
                    processResults: function (data) {
                        return {
                            results: $.map(data, function (item) {
                                return {
                                    text: item.email,
                                    id: item.id,
                                }
                            })
                        };
                    }
                }
            });
        });

        CKEDITOR.replace('ckeditor',
            {
                customConfig: 'config.js',
                toolbar: 'simple'
            });
    </script>
@endsection

resources/views/admin/notifications/edit.blade.php
@extends('templates.admin.master_page')
@section('title_browser')
    ویرایش پیغام
@endsection
@section('style')
    <style>
        .iconpicker {
            overflow: hidden !important;
        }

        #ckeditor {
            display: none;
        }
    </style>
@endsection
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="row align-items-center">
                    <div class="col-md-8">
                        <h3 class="page-title m-0">ویرایش پیغام </h3>
                    </div>
                    <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end page-title-box -->
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('admin.notifications.update',$notification)}}" method="post">
                        @csrf
                        @method('put')
                        <div class="row justify-content-center">
                            <div class="form-group col-lg-10 col-md-4 col-sm-6">
                                <label for="example-text-input" class="">عنوان</label>
                                <input type="text" name="title" class="form-control" value="{{$notification->title}}">
                            </div>

                        </div>
                        <div class="row justify-content-center">
                            <div class="form-group col-lg-10 col-md-4 col-sm-6">
                                <label for="example-text-input" class="">توضیحات</label>
                                <textarea id="ckeditor" name="description" rows="10" cols="125">
                                    {{$notification->description}}
            </textarea>
                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <div class="form-group col-lg-2 col-md-3 col-sm-6 mt-3">
                                <div class="form-check">
                                    <input class="receiver" type="radio" name="receiver" id="exampleRadios1"
                                           value="0" {{ ($notification->user_id==0)?'checked':'' }}>
                                    <label class="form-check-label" for="exampleRadios1">
                                        همه کاربران
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="receiver" type="radio" name="receiver" id="exampleRadios2"
                                           value="1" {{ ($notification->user_id!=0)?'checked':'' }}>
                                    <label class="form-check-label" for="exampleRadios2">
                                        کاربر خاص
                                    </label>
                                </div>

                            </div>
                            @if($notification->user_id)
                                <div class="form-group col-lg-3 col-md-4 col-sm-6">
                                    <label for="example-text-input" class="">کاربران</label>
                                    <select type="text" name="user_id" class="form-control users">
                                        <option value="{{ $notification->user_id }}"
                                                selected="selected">{{ $notification->user }}</option>
                                    </select>
                                </div>
                            @else
                                <div class="form-group col-lg-3 col-md-4 col-sm-6 d-none">
                                    <label for="example-text-input" class="">کاربران</label>
                                    <select id="users" type="text" name="user_id" class="form-control users">
                                        <option value="">انتخاب کنید...</option>
                                    </select>
                                </div>
                            @endif
                            <div class="form-group col-lg-2 col-md-4 col-sm-6">
                                <label for="example-text-input">رنگ پیغام</label>
                                <select name="color" class="form-control">
                                    <option @if($notification->color == 'info') selected @endif value="info">info
                                    </option>
                                    <option @if($notification->color == 'warning') selected @endif value="warning">
                                        warning
                                    </option>
                                    <option @if($notification->color == 'danger') selected @endif value="danger">
                                        danger
                                    </option>
                                </select>
                            </div>
                            <div class="form-group col-lg-4 col-md-4 col-sm-6">
                                <label for="example-text-input" readonly>تاریخ</label>
                                <sub class="text-danger">درصورت تمایل به ارسال در زمان حاضر این فیلد را پر نکنید.</sub>
                                <input name="started_at" class="form-control datePicker"
                                       value="{{$notification->started_at}}" readonly>
                            </div>
                            <div class="form-group col-lg-1 col-md-4 col-sm-6">
                                <label for="example-text-input">آیکون</label>
                                <span class="input-group-prepend">
            <button name="icon" class="btn btn-danger iconpicker" data-icon-select="{{ $notification->icon }}"
                    role="iconpicker"></button>
        </span>

                            </div>
                        </div>
                        <div class="row justify-content-center">
                            <button type="submit" class="btn btn-success btn-lg ajaxStore">ویرایش پیغام</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function () {
            setIconPicker()
            $(document).on('change', '.receiver', function () {
                var val = $(this).val();
                var elem = $(".users").closest(".form-group");
                if (val == 1) {
                    elem.removeClass('d-none');
                } else {
                    elem.addClass('d-none');
                }
            })
            $('.users').select2({
                width: '100%',
                minimumInputLength: 3,
                ajax: {
                    url: `{{ route('admin.notifications.get_user') }}`,
                    dataType: 'json',
                    type: "get",
                    processResults: function (data) {
                        return {
                            results: $.map(data, function (item) {
                                return {
                                    text: item.email,
                                    id: item.id,
                                }
                            })
                        };
                    }
                }
            });
        });
        CKEDITOR.replace('ckeditor',
            {
                customConfig: 'config.js',
                toolbar: 'simple'
            })
    </script>
@endsection