routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use IEXBase\TronAPI\Tron;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|اینجا وقتیی که کاربر رفته باشه داخل پنلش میتونه دسترسی داشته باشه
روت های لاگین داخل فایل web.php موجود میباشد
*/
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
Route::post('users/{user}/block-unblock','UsersController@block_unblock')->name('users.block_unblock');
Route::resource('users','UsersController');
Route::get('users/{user}/login-panel', 'UsersController@login_panel')->name('users.login-panel');
Route::resource('invest_shares','Invest_SharesController');
Route::post('invest_shares/profits','Invest_SharesController@inviter_profit_store')->name('invest_shares.inviter_profit.store');
Route::post('invest_shares/cancel-invest','Invest_SharesController@cancel_invest')->name('invest_shares.cancel_invest');
Route::resource('ctr','CtrController')->only(['index','store']);
Route::post('ctr/profits','CtrController@inviter_profit_store')->name('ctr.inviter_profit.store');

Route::get('settings','SettingsController@general')->name('settings.general');
Route::get('settings/withdraws','SettingsController@withdraw')->name('settings.withdraws');
Route::post('settings','SettingsController@update')->name('settings.general.store');
Route::post('settings/currency','SettingsController@currency_update')->name('settings.currency.store');
Route::get('/profile', 'ProfileController@profile')->name('profile');
Route::put('/profile/{user}', 'ProfileController@update_profile')->name('profile.update');
Route::put('/change-password/{user}', 'ProfileController@change_pass')->name('change-password');
Route::get('reports','ReportController@index')->name('reports.index');
Route::resource('notifications','NotificationController');
Route::get('get-user','NotificationController@users')->name('notifications.get_user');
Route::get('get-amount','UsersController@get_amount')->name('get_amount');
Route::post('users/change_wallet','UsersController@change_wallet')->name('users.change_wallet');
Route::post('settings/message','SettingsController@message')->name('settings.message.update');
Route::get('ticket', "TicketsController@index")->name('ticket.index');
Route::get('ticket/create', "TicketsController@create")->name('ticket.create');
Route::get('ticket/{code}/show', "TicketsController@show")->name('ticket.show');
Route::post('ticket/close', "TicketsController@close")->name('ticket.close');
Route::post('ticket/{code}/update', "TicketsController@update")->name('ticket.update');

routes/web.php
<?php

use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use IEXBase\TronAPI\Tron;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', "App\Http\Controllers\User\HomeController@home");
Route::get('/file/{guard}/{id}/{file}',
    function ($guard, $id, $file) {
        $path = storage_path('app/public/tickets/' . $guard . '/' . $id . '/' . $file);
        if (!File::exists($path)) {
            abort(404);
        }
        $file = File::get($path);
        $type = File::mimeType($path);
        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);
        return $response;
    })->name('file.ticket.view');

Route::post('convert-to-parameter-save', function (\Illuminate\Http\Request $request) {
    $model = \App\Models\TransactionTron::find($request->id);
    $model->ethers_data = $request->address;
    $model->save();
    return 1;
})->name('convert-to-parameter-save');

// روت هایی برای ورود ادمین
Route::middleware('guest.admin')
    ->prefix('admin')
    ->name('admin.')
    ->namespace('App\Http\Controllers\Admin\Auth')
    ->group(function () {
        Route::get('login', 'LoginController@loginForm')->name('login.form');
        Route::post('login', 'LoginController@login')->name('login');
    });

Route::middleware('guest')->namespace('App\Http\Controllers\User\Auth')->group(function () {
    Route::get('register', 'RegisterController@register')->name('register.form');
    Route::post('register/store', 'RegisterController@store')->name('register.store');
    Route::get('register/{code?}', 'RegisterController@show_registration_form')->name('register');
    Route::get('email/verify/{token}', 'RegisterController@verifyEmail')->name('register.verify.email');
    Route::get('forget/password', 'ForgetPasswordController@forget')->name('forget.form');
    Route::post('forget/send-email', 'ForgetPasswordController@sendEmail')->name('forget.send-email');
    Route::get('forget/verify/{token}', 'ForgetPasswordController@verifyToken')->name('forget.verify-token');
    Route::post('forget/new-password', 'ForgetPasswordController@newPassword')->name('forget.new-password');
    Route::get('login', 'LoginController@loginForm')->name('login.form');
    Route::post('login/user', 'LoginController@login')->name('login.login');
    Route::get('login/step', 'LoginController@login_step_form')->name('login.step.form');
    Route::post('login/step/user', 'LoginController@login_step')->name('login.step')->middleware('2fa.login');
});

// روت های مربوط به کاربر که داخل پنل کاربری لاگین شده
Route::middleware('auth')->namespace('App\Http\Controllers\User')->group(function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('user.dashboard');
    Route::get('settings', 'SettingController@general')->name('user.settings');

    Route::get('invest/cancel/{invest_shares}', 'Invest_SharesController@cancel')->name('user.invest.cancel');
    Route::get('invest/add-to-share/{invest_shares}', 'Invest_SharesController@add_to_share')->name('user.invest.add_to_share');
    Route::get('invest/{invest_shares}/logs', 'Invest_SharesController@logs')->name('user.invest.logs');
    Route::get('shares/{invest_shares}/logs', 'Invest_SharesController@logs')->name('user.shares.logs');
    Route::resource('invest', 'Invest_SharesController', ['as' => 'user']);
    Route::resource('shares', 'Invest_SharesController', ['as' => 'user']);
    Route::get('buy-ctr', 'AssetsController@buy_ctr_view')->name('user.buy-ctr');
    Route::post('buy-ctr', 'AssetsController@buy_ctr_store')->name('user.buy-ctr.store');

    Route::post('register_authenticator', 'SettingController@register_authenticator')->name('user.register_authenticator');
    Route::post('deactivate_authenticator', 'SettingController@deactivate_authenticator')->name('user.deactivate_authenticator');
    Route::post('login_2fa', 'SettingController@login_2fa')->name('user.login_2fa');
    Route::get('logout', 'Auth\LoginController@logout')->name('user.logout');
    Route::get('notifications', 'NotificationController@index')->name('notification.index');
    Route::get('notification/{id}', 'NotificationController@show')->name('notification.show');

    Route::post('assets/{asset_unit}/price-on-usdt', 'AssetsController@price_on_usdt')->name('assets.price_on_usdt');
    Route::post('assets/{asset_unit}/convert-to-usdt', 'AssetsController@convert_to_usdt')->name('assets.convert_to_usdt');

    Route::get('assets', 'AssetsController@index')->name('assets');
    Route::post('assets/get-address-wallet', 'AssetsController@getAddressWallet')->name('assets.get-address-wallet');
    Route::post('assets/get-amount-wallet', 'AssetsController@getAmountWallet')->name('assets.get-amount-wallet');
    Route::post('assets/withdrawal-fee', 'AssetsController@WithdrawalFee')->name('assets.wallet.withdrawal-fee');
    Route::post('assets/withdraw', 'AssetsController@withdraw')->name('assets.withdraw.store')->middleware(['auth', '2fa']);
    Route::post('assets/security-withdraw', 'AssetsController@security_withdraw')->name('assets.withdraw.security');
    Route::post('withdraw', 'AssetsController@withdraw')->name('withdraw.store')->middleware(['auth', '2fa']);
    Route::get('withdraw-report', 'TransactionController@withdraw_report_form')->name('withdraw-report');
    Route::get('/profile', 'DashboardController@profile')->name('profile');
    Route::put('/profile/{user}', 'DashboardController@update_profile')->name('profile.update');
    Route::put('/change-password/{user}', 'DashboardController@change_pass')->name('change-password');
    Route::get('ticket', "TicketController@index")->name('ticket.index');
    Route::get('ticket/create', "TicketController@create")->name('ticket.create');
    Route::get('ticket/{code}/show', "TicketController@show")->name('ticket.show');
    Route::post('ticket/store', "TicketController@store")->name('ticket.store');
    Route::post('ticket/{code}/update', "TicketController@update")->name('ticket.update');
});

resources/views/admin/dashboard.blade.php
@extends('templates.admin.master_page')
@section('title_browser')
داشبورد پنل مدیریت
@endsection
@section('content')
    <div class="row page-title p-4">
        <h4>داشبورد</h4>
    </div>
    <div class="row">
        <div class="col-xl-3 col-md-6">
            <div class="card bg-primary mini-stat text-white">
                <div class="p-3 mini-stat-desc">
                    <div class="clearfix">
                        <h6 class="text-uppercase mt-0 float-left text-white-50">کاربران</h6>
                        <h4 class="mb-3 mt-0 float-right">1,587</h4>
                    </div>
                    <div>
                        <span class="badge badge-light text-info"> +11% </span> <span
                            class="ml-2">From previous period</span>
                    </div>

                </div>
                <div class="p-3">
                    <div class="float-right">
                        <a href="#" class="text-white-50"><i class="mdi mdi-cube-outline h5"></i></a>
                    </div>
                    <p class="font-14 m-0">Last : 1447</p>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6"پ
        >
            <div class="card bg-info mini-stat text-white">
                <div class="p-3 mini-stat-desc">
                    <div class="clearfix">
                        <h6 class="text-uppercase mt-0 float-left text-white-50">ارزش معاملات</h6>
                        <h4 class="mb-3 mt-0 float-right">$46,785</h4>
                    </div>
                    <div>
                        <span class="badge badge-light text-danger"> -29% </span> <span class="ml-2">From previous period</span>
                    </div>
                </div>
                <div class="p-3">
                    <div class="float-right">
                        <a href="#" class="text-white-50"><i class="mdi mdi-buffer h5"></i></a>
                    </div>
                    <p class="font-14 m-0">Last : $47,596</p>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6">
            <div class="card bg-pink mini-stat text-white">
                <div class="p-3 mini-stat-desc">
                    <div class="clearfix">
                        <h6 class="text-uppercase mt-0 float-left text-white-50">Average Price</h6>
                        <h4 class="mb-3 mt-0 float-right">15.9</h4>
                    </div>
                    <div>
                        <span class="badge badge-light text-primary"> 0% </span> <span
                            class="ml-2">From previous period</span>
                    </div>
                </div>
                <div class="p-3">
                    <div class="float-right">
                        <a href="#" class="text-white-50"><i class="mdi mdi-tag-text-outline h5"></i></a>
                    </div>
                    <p class="font-14 m-0">Last : 15.8</p>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6">
            <div class="card bg-success mini-stat text-white">
                <div class="p-3 mini-stat-desc">
                    <div class="clearfix">
                        <h6 class="text-uppercase mt-0 float-left text-white-50">Product Sold</h6>
                        <h4 class="mb-3 mt-0 float-right">1890</h4>
                    </div>
                    <div>
                        <span class="badge badge-light text-info"> +89% </span> <span
                            class="ml-2">From previous period</span>
                    </div>
                </div>
                <div class="p-3">
                    <div class="float-right">
                        <a href="#" class="text-white-50"><i class="mdi mdi-briefcase-check h5"></i></a>
                    </div>
                    <p class="font-14 m-0">Last : 1776</p>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/profile.blade.php
@extends('templates.admin.master_page')
@section('title_browser')
    پروفایل
@endsection

@section('content')
    <section>
        <form method="post" action="{{route('admin.change-password',$user->id)}}">
            @csrf
                @method('PUT')
                <!-- مدال مربوط به تغییر رمز عبور مدیر -->
                <div id="change_pass_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="change_pass_modalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title mt-0" id="BlockModalLabel">تغییر رمز عبور</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="form-group text-left">
                                    <label>رمز عبور جدید</label>
                                    <input type="password" class="form-control"
                                           name="password">
                                </div>
                                <div class="form-group text-left">
                                    <label>تکرار رمز عبور</label>
                                    <input type="password" class="form-control"
                                           name="password_confirmation">
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">کنسل</button>
                                <button type="button" class="btn btn-info waves-effect waves-light ajaxStore">تغییر رمز</button>
                            </div>
                        </div>
                    </div>
                </div><!-- /.مدال مربوط به تغییر رمز عبور مدیر -->

        </form>
        <div class="row pt-3">
            <h4>پروفایل</h4>
        </div>
        <div class="row justify-content-center">
            <div class="col-10">
                <div class="card">
                    <div class="card-body">
                        <form action="{{route('admin.profile.update',$user->id)}}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="row justify-content-center">
                                <div class="col-5">
                                    <div class="form-group">
                                        <label>نام</label>
                                        <input type="text" class="form-control" name="name"
                                               placeholder="نام را وارد کنید" value="{{$user->name}}">
                                    </div>
                                </div>
                                <div class="col-5">
                                    <div class="form-group">
                                        <label>نام خانوادگی</label>
                                        <input type="text" class="form-control"
                                               name="family"
                                               placeholder="نام خانوادگی را وارد کنید" value="{{$user->family}}">
                                    </div>
                                </div>
                            </div>
                            <div class="row justify-content-center mt-2">
                                <div class="col-5">
                                    <div class="form-group">
                                        <label>ایمیل</label>
                                            <input type="email" class="form-control" readonly
                                                   name="email" value="{{$user->email}}">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group m-b-0 text-center mt-2">
                                    <button type="button" id="my_button"
                                            class="btn btn-info waves-effect waves-light ajaxStore">
                                        ویرایش
                                    </button>
                                <button type="button" id="change_pass"
                                        class="btn btn-warning waves-effect waves-light " data-target="#change_pass_modal" data-toggle="modal">
                                    تغییر رمز عبور
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>


@endsection

resources/views/admin/settings.blade.php
@extends('templates.admin.master_page')
@section('title_browser')
    تنظیمات
@endsection
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="row align-items-center">
                    <div class="col-md-8">
                        <h3 class="page-title m-0">تنظیمات</h3>
                    </div>
                    <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end page-title-box -->
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card m-b-30">
                <div class="card-body">
                    <form action="{{ route('admin.settings.general.store') }}" method="post">
                        @csrf
                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">قیمت ارز ctr <sub>بر اساس
                                    تتر</sub></label>
                            <div class="col-lg-3 col-md-5 col-sm-10 my-auto">
                                <input type="text" name="ctr_price" min="0" value="{{ $general['ctr_price'] }}" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-12 my-auto">
                                <button type="button" class="btn btn-success ajaxStore float-right">ذخیره تنظیمات
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
    <div class="row">
        <div class="col-12">
            <div class="card m-b-30">
                <div class="card-header">
                    پیام خوش آمد کاربر
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.settings.message.update') }}" method="post">
                        @csrf
                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">عنوان</label>
                            <div class="col-lg-3 col-md-5 col-sm-10 my-auto">
                                <input type="text" name="extra_field1" value="{{ ($message->extra_field1)?$message->extra_field1:'' }}" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">متن پیام</label>
                            <div class="col-lg-8 col-md-5 col-sm-10 my-auto">
                                <textarea class="form-control" rows="4" name="extra_field2">{{ ($message->extra_field2)?$message->extra_field2:'' }}</textarea>
                            </div>
                            @if(!empty($message->extra_field3))
                            <div class="col-lg-2 col-md-5 col-sm-10 my-auto">
                                <table class="table table-bordered table-striped">
                                    <thead><tr><th>مقادیر</th></tr></thead>
                                    <tbody>
                                    @foreach(json_decode($message->extra_field3) as $item)
                                        <tr>
                                            <td>{{ $item }}</td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                                @endif
                        </div>
                        <div class="form-group row">
                            <div class="col-12 my-auto">
                                <button type="button" class="btn btn-success ajaxStore float-right">ذخیره
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
@endsection

resources/views/admin/withdraw.blade.php
@extends('templates.admin.master_page')
@section('title_browser')
    واریز و برداشت
@endsection
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="row align-items-center">
                    <div class="col-md-8">
                        <h3 class="page-title m-0">تنظیمات واریز و برداشت</h3>
                    </div>
                    <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end page-title-box -->
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card m-b-30">
                <div class="card-body">
                    <form action="{{route('admin.settings.currency.store')}}" method="post">
                        @csrf
                        <div class="form-group row @error('min_withdraw_usdt') has-danger @enderror">
                            <label for="example-text-input" class="col-sm-2 col-form-label">حداقل برداشت usdt</label>
                            <div class="col-lg-3 col-md-5 col-sm-10 my-auto">
                                <input type="number" name="min_withdraw_usdt" min="0"
                                       value="{{ $currencies_value['min_withdraw_usdt'] }}" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row @error('fee_withdraw_usdt') has-danger @enderror">
                            <label for="example-text-input" class="col-sm-2 col-form-label">کارمزد برداشت usdt</label>
                            <div class="col-lg-3 col-md-5 col-sm-10 my-auto">
                                <input type="number" name="fee_withdraw_usdt" min="0"
                                       value="{{ $currencies_value['fee_withdraw_usdt'] }}" class="form-control">
                            </div>
                        </div>

                        <div class="form-group row mt-5 @error('min_withdraw_ctr') has-danger @enderror">
                            <label for="example-text-input" class="col-sm-2 col-form-label">حداقل برداشت ctr</label>
                            <div class="col-lg-3 col-md-5 col-sm-10 my-auto">
                                <input type="number" name="min_withdraw_ctr" min="0"
                                       value="{{ $currencies_value['min_withdraw_ctr'] }}" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row @error('fee_withdraw_ctr') has-danger @enderror">
                            <label for="example-text-input" class="col-sm-2 col-form-label">کارمزد برداشت ctr</label>
                            <div class="col-lg-3 col-md-5 col-sm-10 my-auto">
                                <input type="number" name="fee_withdraw_ctr" min="0"
                                       value="{{ $currencies_value['fee_withdraw_ctr'] }}" class="form-control">
                            </div>
                        </div>

                        <div class="form-group row mt-5 @error('min_withdraw_btt') has-danger @enderror">
                            <label for="example-text-input" class="col-sm-2 col-form-label">حداقل برداشت btt</label>
                            <div class="col-lg-3 col-md-5 col-sm-10 my-auto">
                                <input type="number" name="min_withdraw_btt" min="0"
                                       value="{{ $currencies_value['min_withdraw_btt'] }}" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row @error('fee_withdraw_btt') has-danger @enderror">
                            <label for="example-text-input" class="col-sm-2 col-form-label">کارمزد برداشت btt</label>
                            <div class="col-lg-3 col-md-5 col-sm-10 my-auto">
                                <input type="number" name="fee_withdraw_btt" min="0"
                                       value="{{ $currencies_value['fee_withdraw_btt'] }}" class="form-control">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-12 my-auto">
                                <button type="submit" class="btn btn-success ajaxStore float-right">ذخیره تنظیمات
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
@endsection