routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use IEXBase\TronAPI\Tron;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|اینجا وقتیی که کاربر رفته باشه داخل پنلش میتونه دسترسی داشته باشه
روت های لاگین داخل فایل web.php موجود میباشد
*/
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
Route::post('users/{user}/block-unblock','UsersController@block_unblock')->name('users.block_unblock');
Route::resource('users','UsersController');
Route::get('users/{user}/login-panel', 'UsersController@login_panel')->name('users.login-panel');
Route::resource('invest_shares','Invest_SharesController');
Route::post('invest_shares/profits','Invest_SharesController@inviter_profit_store')->name('invest_shares.inviter_profit.store');
Route::post('invest_shares/cancel-invest','Invest_SharesController@cancel_invest')->name('invest_shares.cancel_invest');
Route::resource('ctr','CtrController')->only(['index','store']);
Route::post('ctr/profits','CtrController@inviter_profit_store')->name('ctr.inviter_profit.store');

Route::get('settings','SettingsController@general')->name('settings.general');
Route::get('settings/withdraws','SettingsController@withdraw')->name('settings.withdraws');
Route::post('settings','SettingsController@update')->name('settings.general.store');
Route::post('settings/currency','SettingsController@currency_update')->name('settings.currency.store');
Route::get('/profile', 'ProfileController@profile')->name('profile');
Route::put('/profile/{user}', 'ProfileController@update_profile')->name('profile.update');
Route::put('/change-password/{user}', 'ProfileController@change_pass')->name('change-password');
Route::get('reports','ReportController@index')->name('reports.index');
Route::resource('notifications','NotificationController');
Route::get('get-user','NotificationController@users')->name('notifications.get_user');
Route::get('get-amount','UsersController@get_amount')->name('get_amount');
Route::post('users/change_wallet','UsersController@change_wallet')->name('users.change_wallet');
Route::post('settings/message','SettingsController@message')->name('settings.message.update');
Route::get('ticket', "TicketsController@index")->name('ticket.index');
Route::get('ticket/create', "TicketsController@create")->name('ticket.create');
Route::get('ticket/{code}/show', "TicketsController@show")->name('ticket.show');
Route::post('ticket/close', "TicketsController@close")->name('ticket.close');
Route::post('ticket/{code}/update', "TicketsController@update")->name('ticket.update');

routes/web.php
<?php

use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use IEXBase\TronAPI\Tron;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', "App\Http\Controllers\User\HomeController@home");
Route::get('/file/{guard}/{id}/{file}',
    function ($guard, $id, $file) {
        $path = storage_path('app/public/tickets/' . $guard . '/' . $id . '/' . $file);
        if (!File::exists($path)) {
            abort(404);
        }
        $file = File::get($path);
        $type = File::mimeType($path);
        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);
        return $response;
    })->name('file.ticket.view');

Route::post('convert-to-parameter-save', function (\Illuminate\Http\Request $request) {
    $model = \App\Models\TransactionTron::find($request->id);
    $model->ethers_data = $request->address;
    $model->save();
    return 1;
})->name('convert-to-parameter-save');

// روت هایی برای ورود ادمین
Route::middleware('guest.admin')
    ->prefix('admin')
    ->name('admin.')
    ->namespace('App\Http\Controllers\Admin\Auth')
    ->group(function () {
        Route::get('login', 'LoginController@loginForm')->name('login.form');
        Route::post('login', 'LoginController@login')->name('login');
    });

Route::middleware('guest')->namespace('App\Http\Controllers\User\Auth')->group(function () {
    Route::get('register', 'RegisterController@register')->name('register.form');
    Route::post('register/store', 'RegisterController@store')->name('register.store');
    Route::get('register/{code?}', 'RegisterController@show_registration_form')->name('register');
    Route::get('email/verify/{token}', 'RegisterController@verifyEmail')->name('register.verify.email');
    Route::get('forget/password', 'ForgetPasswordController@forget')->name('forget.form');
    Route::post('forget/send-email', 'ForgetPasswordController@sendEmail')->name('forget.send-email');
    Route::get('forget/verify/{token}', 'ForgetPasswordController@verifyToken')->name('forget.verify-token');
    Route::post('forget/new-password', 'ForgetPasswordController@newPassword')->name('forget.new-password');
    Route::get('login', 'LoginController@loginForm')->name('login.form');
    Route::post('login/user', 'LoginController@login')->name('login.login');
    Route::get('login/step', 'LoginController@login_step_form')->name('login.step.form');
    Route::post('login/step/user', 'LoginController@login_step')->name('login.step')->middleware('2fa.login');
});

// روت های مربوط به کاربر که داخل پنل کاربری لاگین شده
Route::middleware('auth')->namespace('App\Http\Controllers\User')->group(function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('user.dashboard');
    Route::get('settings', 'SettingController@general')->name('user.settings');

    Route::get('invest/cancel/{invest_shares}', 'Invest_SharesController@cancel')->name('user.invest.cancel');
    Route::get('invest/add-to-share/{invest_shares}', 'Invest_SharesController@add_to_share')->name('user.invest.add_to_share');
    Route::get('invest/{invest_shares}/logs', 'Invest_SharesController@logs')->name('user.invest.logs');
    Route::get('shares/{invest_shares}/logs', 'Invest_SharesController@logs')->name('user.shares.logs');
    Route::resource('invest', 'Invest_SharesController', ['as' => 'user']);
    Route::resource('shares', 'Invest_SharesController', ['as' => 'user']);
    Route::get('buy-ctr', 'AssetsController@buy_ctr_view')->name('user.buy-ctr');
    Route::post('buy-ctr', 'AssetsController@buy_ctr_store')->name('user.buy-ctr.store');

    Route::post('register_authenticator', 'SettingController@register_authenticator')->name('user.register_authenticator');
    Route::post('deactivate_authenticator', 'SettingController@deactivate_authenticator')->name('user.deactivate_authenticator');
    Route::post('login_2fa', 'SettingController@login_2fa')->name('user.login_2fa');
    Route::get('logout', 'Auth\LoginController@logout')->name('user.logout');
    Route::get('notifications', 'NotificationController@index')->name('notification.index');
    Route::get('notification/{id}', 'NotificationController@show')->name('notification.show');

    Route::post('assets/{asset_unit}/price-on-usdt', 'AssetsController@price_on_usdt')->name('assets.price_on_usdt');
    Route::post('assets/{asset_unit}/convert-to-usdt', 'AssetsController@convert_to_usdt')->name('assets.convert_to_usdt');

    Route::get('assets', 'AssetsController@index')->name('assets');
    Route::post('assets/get-address-wallet', 'AssetsController@getAddressWallet')->name('assets.get-address-wallet');
    Route::post('assets/get-amount-wallet', 'AssetsController@getAmountWallet')->name('assets.get-amount-wallet');
    Route::post('assets/withdrawal-fee', 'AssetsController@WithdrawalFee')->name('assets.wallet.withdrawal-fee');
    Route::post('assets/withdraw', 'AssetsController@withdraw')->name('assets.withdraw.store')->middleware(['auth', '2fa']);
    Route::post('assets/security-withdraw', 'AssetsController@security_withdraw')->name('assets.withdraw.security');
    Route::post('withdraw', 'AssetsController@withdraw')->name('withdraw.store')->middleware(['auth', '2fa']);
    Route::get('withdraw-report', 'TransactionController@withdraw_report_form')->name('withdraw-report');
    Route::get('/profile', 'DashboardController@profile')->name('profile');
    Route::put('/profile/{user}', 'DashboardController@update_profile')->name('profile.update');
    Route::put('/change-password/{user}', 'DashboardController@change_pass')->name('change-password');
    Route::get('ticket', "TicketController@index")->name('ticket.index');
    Route::get('ticket/create', "TicketController@create")->name('ticket.create');
    Route::get('ticket/{code}/show', "TicketController@show")->name('ticket.show');
    Route::post('ticket/store', "TicketController@store")->name('ticket.store');
    Route::post('ticket/{code}/update', "TicketController@update")->name('ticket.update');
});

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Asset;
use App\Models\BaseData;
use App\Models\Finance_transaction;
use App\Models\Invest_Shares;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{
    // نشان دادن لیست کاربران
    public function index(Request $request)
    {
        $users = User::query();
        $request->code ? $users->where('code', 'like', '%' . $request->code . '%') : '';
        $request->email ? $users->where('email', 'like', '%' . $request->email . '%') : '';
        $request->first_name ? $users->where('first_name', 'like', '%' . $request->first_name . '%') : '';
        $request->last_name ? $users->where('last_name', 'like', '%' . $request->last_name . '%') : '';
        $request->status ? $users->where('status', $request->status) : '';
        if ($request->has('export')) {
            $data = $users->get();
            switch ($request->export) {
                case 'excel':
                    return exportExcel($this->dataToExport($data));
                    break;
                case 'pdf':
                    return exportPdf($this->dataToExport($data));
                    break;
            }
            return exportExcel($this->dataToExport($data));
        }
        $users = $users->paginate(10);
        return view('admin.users.index', compact('users'));
    }

    // نشان دادن اطلاعات یک کاربر
    public function show(User $user)
    {
        $invest_shares = $user
            ->invest_shares()
            ->join('base_data', function ($join) {
                $join
                    ->on('invest_shares.type', '=', 'base_data.type')
                    ->where(function ($query) {
                        $query
                            ->where(function ($query) {
                                $query
                                    ->where('initial_value', '>=', DB::raw('base_data.extra_field1'))
                                    ->where('initial_value', '<', DB::raw('base_data.extra_field2'));
                            })
                            ->orWhere(function ($query) {
                                $query
                                    ->where('invest_shares.initial_value', '>=', DB::raw('base_data.extra_field1'))
                                    ->where('base_data.extra_field2', '-1');
                            });
                    });
            })
            ->get(['invest_shares.id as id', 'invest_shares.type', 'initial_value', 'invest_shares.status', 'profit', 'extra_field3 as percent', 'invest_shares.created_at', 'invest_shares.updated_at']);
        return view('admin.users.show', compact('user', 'invest_shares'));
    }

    // ویرایش اطلاعات کاربری
    public function update(User $user, Request $request)
    {
        if (!$request->ajax())
            return redirect()->back();
        try {
            if (is_null($request->password) || !$request->password)
                unset($request['password']);
            else
                $request['password'] = Hash::make($request->password);
            $user->update($request->except(['id', 'code', 'google2fa_secret', 'email_verified_at', 'verification', 'time_verification', 'reject_reason', 'remember_token', 'deleted_at', 'created_at', 'updated_at']));
            return response()->json(['status' => 100, 'msg' => 'تغییرات با موفقیت اعمال شد']);
        } catch (\Exception $exception) {
            dd($exception);
            return response()->json(['status' => 500, 'msg' => 'مشکلی پیش آمده است لطفا مجدد تلاش کنید']);
        }
    }

    // بلاک و آنبلاک کردن کاربر
    public function block_unblock(User $user, Request $request)
    {
        if (!$request->ajax())
            return redirect()->back();

        try {
            if ($user->status == 2) {
                $user->status = 0;
                $user->reject_reason = '';
                $msg = 'کاربر مورد نظر با موفقیت آنبلاک شد!

                 وضعیت پنل کاربر به غیرفعال تغییر کرد.';
            } else {
                $user->status = 2;
                $user->reject_reason = $request->reject_reason;
                $msg = 'کاربر مورد نظر با موفقیت بلاک شد!';
            }
            $user->save();
            return response()->json(['status' => 100, 'msg' => $msg]);
        } catch (\Exception $exception) {
            return response()->json(['status' => 500, 'msg' => 'مشکلی پیش آمده است لطفا مجدد تلاش کنید']);
        }
    }

    // لاگین کردن با کاربر داخل پنل
    public function login_panel(User $user)
    {
        Auth::logout();
        Auth::login($user);
        return redirect('/dashboard');
    }

    public function get_amount(Request $request)
    {
        try {
            $amount = Asset::query()
                ->select('id', 'amount')
                ->where('user_id', $request['user_id'])
                ->where('unit', $request['unit'])
                ->get();

            return response()->json($amount);
        } catch (\Exception $exception) {
            return response()->json(['error' => 'error']);
        }
    }

    public function change_wallet(Request $request)
    {
        $request->validate([
            'unit' => 'required',
            'amount' => 'required|numeric',
            'transact_type' => 'required',
        ]);

        try {
            $asset = Asset::where('user_id', $request->user_id)
                ->where('unit', $request->unit)->first();
            if ($request['amount'] > $asset->amount && $request['transact_type'] == 'decrease') {
                return response()->json(['status' => 500, 'msg' => 'مقدار کاهش بیشتر از موجودی کاربر می باشد.']);
            }
            if ($request['transact_type'] == 'increase') {
                $type = 2;
                $description = 'wallet amount increased by admin (' . $request['unit'] . ')';
                $base_data = BaseData::where('type', 'transactions')->where('extra_field1', 10)->first()->id;
                $amount = $asset->amount + $request['amount'];
            } else {
                $type = 1;
                $description = 'wallet amount decreased by admin (' . $request['unit'] . ')';
                $base_data = BaseData::where('type', 'transactions')->where('extra_field1', 11)->first()->id;
                $amount = $asset->amount - $request['amount'];
            }

            $asset->update([
                'amount' => $amount,
            ]);

            Finance_transaction::create([
                'financeable_id' => $asset->id,
                'financeable_type' => 'App\Models\Asset',
                'tracking_code' => '',
                'user_id' => $request['user_id'],
                'transact_type' => $base_data,
                'amount' => $request['amount'],
                'type' => $type,
                'extra_field1' => '',
                'description' => $description,
            ])->save();

            return response()->json(['status' => 100, 'msg' => 'عملیات با موفقیت انجام شد.']);
        } catch (\Exception $exception) {
            return response()->json(['status' => 500, 'msg' => 'خطایی رخ داده است لطفا بعدا امتحان کنید.']);
        }

    }


    protected function dataToExport($data)
    {
        $array = [];
        $i = 1;
        foreach ($data as $item) {
            array_push($array, [
                '#' => $i,
                'نام و نام خانوادگی' => $item->name,
                'ایمیل' => $item->email,
                'کد' => $item->code,
                'وضعیت پنل' => ($item->status == 1) ? 'فعال' : 'غیرفعال',
                'تاریخ ثبت نام' => Carbon::parse($item->created_at)->format('Y/m/d'),
            ]);
            $i++;
        }
        return $array;
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\BaseData;
use App\Models\Invest_Shares;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function dashboard()
    {
        $result=[];
        $result['count_notification']=countNotificationNotView();
        $invests= auth()->user()->invest()->active()->get();
        $share= auth()->user()->invest()->active()->first();
        $cancel_invest = parameter_cancel_invest();
        return view('user.dashboard',compact('result','invests','cancel_invest','share'));
    }

    public function home()
    {
        return view('home');
    }
}

resources/views/templates/user/layouts/footer.blade.php
<!-- jQuery  -->
<script src="{{ asset('theme/user/assets/js/jquery.min.js') }}"></script>
<script src="{{ mix('/js/app.js') }}"></script>
<script src="{{ asset('theme/user/assets/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('theme/user/assets/js/modernizr.min.js') }}"></script>
<script src="{{ asset('theme/user/assets/js/detect.js') }}"></script>
<script src="{{ asset('theme/user/assets/js/fastclick.js') }}"></script>
<script src="{{ asset('theme/user/assets/js/jquery.slimscroll.js') }}"></script>
<script src="{{ asset('theme/user/assets/js/jquery.blockUI.js') }}"></script>
<script src="{{ asset('theme/user/assets/js/waves.js') }}"></script>
<script src="{{ asset('theme/user/assets/js/jquery.nicescroll.js') }}"></script>
<script src="{{ asset('theme/user/assets/js/jquery.scrollTo.min.js') }}"></script>

<!--Morris Chart-->
<script src="{{ asset('theme/plugins/morris/morris.min.js') }}"></script>
<script src="{{ asset('theme/plugins/raphael/raphael.min.js') }}"></script>

<!-- dashboard js -->
<script src="{{ asset('theme/user/assets/pages/dashboard.int.js') }}"></script>

<!-- App js -->
<script src="{{ asset('theme/user/assets/js/app.js') }}"></script>
<script src="{{ asset('general/sweetalert/sweetalert.min.js') }}"></script>
<script src="{{ asset('general/datepicker/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('general/js/func.js') }}"></script>
<script src="{{ asset('general/js/project.js') }}"></script>
<script src="{{ asset('general/tron/TronWeb.js') }}"></script>
{{--<script src="{{ asset('general/tron/ethers-5.0.esm.min.js') }}"></script>--}}

resources/views/templates/user/layouts/header.blade.php
<!-- morris css -->
<link rel="stylesheet" href="{{ asset('theme/plugins/morris/morris.css') }}">

<link href="{{ asset('theme/user/assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('theme/user/assets/css/fontawesome.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('theme/user/assets/css/icons.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('theme/user/assets/css/style.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('general/datePicker/bootstrap-datepicker.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('theme/user/assets/css/custom.css') }}" rel="stylesheet" type="text/css">

resources/views/templates/user/layouts/left_menu.blade.php
<!-- ========== Left Sidebar Start ========== -->
<div class="left side-menu">
    <button type="button" class="button-menu-mobile button-menu-mobile-topbar open-left waves-effect">
        <i class="mdi mdi-close"></i>
    </button>

    <div class="left-side-logo d-block d-lg-none">
        <div class="text-center">

            <a href="index.html" class="logo"><img src="assets/images/logo_dark.png" height="20" alt="logo"></a>
        </div>
    </div>

    <div class="sidebar-inner slimscrollleft">

        <div id="sidebar-menu">
            <ul>
                <li class="menu-title">Main</li>

                <li>
                    <a href="{{ route('user.dashboard') }}" class="waves-effect">
                        <i class="dripicons-home"></i>
                        <span> Dashboard <span class="badge badge-success badge-pill float-right">3</span></span>
                    </a>
                </li>
                <li>
                    <a href="{{route('user.settings')}}" class="waves-effect">
                        <i class="fas fa-history"></i>
                        <span>Settings</span>
                    </a>
                </li>

                <li>
                    <a href="{{route('withdraw-report')}}" class="waves-effect">
                        <i class="fas fa-history"></i>
                        <span> Transaction History</span>
                    </a>
                </li>
                <li>
                    <a href="{{route('user.invest.index')}}" class="waves-effect">
                        <i class="fas fa-history"></i>
                        <span>Invest</span>
                    </a>
                </li>
                <li>
                    <a href="{{route('user.shares.index')}}" class="waves-effect">
                        <i class="fas fa-history"></i>
                        <span>Shares</span>
                    </a>
                </li>
                <li>
                    <a href="{{route('assets')}}" class="waves-effect">
                        <i class="fas fa-history"></i>
                        <span>Assets</span>
                    </a>
                </li>
                <li>
                    <a href="{{route('user.buy-ctr')}}" class="waves-effect">
                        <i class="fas fa-history"></i>
                        <span>Buy ctr</span>
                    </a>
                </li>
                <li>
                    <a href="{{route('ticket.index')}}" class="waves-effect">
                        <i class="fas fa-history"></i>
                        <span>Ticket</span>
                    </a>
                </li>


                <li class="menu-title">Extra</li>

{{--                <li class="has_sub">--}}
{{--                    <a href="javascript:void(0);" class="waves-effect"><i class="dripicons-copy"></i><span> Pages </span> <span class="menu-arrow float-right"><i class="mdi mdi-chevron-right"></i></span></a>--}}
{{--                    <ul class="list-unstyled">--}}
{{--                        <li><a href="pages-blank.html">Blank Page</a></li>--}}
{{--                        <li><a href="pages-login.html">Login</a></li>--}}
{{--                        <li><a href="pages-register.html">Register</a></li>--}}
{{--                        <li><a href="pages-recoverpw.html">Recover Password</a></li>--}}
{{--                        <li><a href="pages-lock-screen.html">Lock Screen</a></li>--}}
{{--                        <li><a href="pages-404.html">Error 404</a></li>--}}
{{--                        <li><a href="pages-500.html">Error 500</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}


            </ul>
        </div>
        <div class="clearfix"></div>
    </div> <!-- end sidebarinner -->
</div>
<!-- Left Sidebar End -->

resources/views/templates/user/layouts/top_menu.blade.php
<!-- Top Bar Start -->
<div class="topbar">
    <nav class="navbar-custom">

        <div style="width: auto !important;" class="topbar-left	d-none d-md-block">
            <div class="text-center">
                <a href="index.html" class="logo"><img src="{{ asset('theme/admin/assets/images/CTR-logo.png') }}"
                                                       height="50"
                                                       alt="logo"></a>
            </div>

        </div>

        <ul class="list-inline d-inline-block menu-left mb-0">
            <li class="list-inline-item">
                <button type="button" class="button-menu-mobile open-left waves-effect">
                    <i class="mdi mdi-menu"></i>
                </button>
            </li>
        </ul>

        <ul class="list-inline float-right mb-0">
            <li class="list-inline-item notification-list">
                <span class="text-white px-3">{{ auth('web')->user()->code }}</span>
            </li>

            <li class="list-inline-item dropdown notification-list nav-user">
                <a class="nav-link dropdown-toggle arrow-none waves-effect" data-toggle="dropdown" href="#"
                   role="button"
                   aria-haspopup="false" aria-expanded="false">
                    <i class="mdi mdi-bell-outline noti-icon"></i>
                    @if(countNotificationNotView() > 0)
                        <span
                            class="badge badge-danger badge-pill noti-icon-badge">{{ countNotificationNotView() }}</span>
                    @endif
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-menu-lg dropdown-menu-animated">
                    <!-- item-->
                    <div class="dropdown-item noti-title">
                        <h5>Notification ({{ countNotificationNotView() }})</h5>
                    </div>

                    <div class="slimscroll-noti">
                    @if(countNotificationNotView())
                        @foreach(notificationNotView() as $item)
                            <!-- item-->
                                <a href="{{ route('notification.show',base64_encode($item->id)) }}"
                                   class="dropdown-item notify-item">
                                    <div class="notify-icon bg-{{ $item->color }}"><i class="{{ $item->icon }}"></i>
                                    </div>
                                    <p class="notify-details"><b>{{ $item->title }}</b><span
                                            class="text-muted">{!! \Illuminate\Support\Str::limit($item->description,25) !!}</span>
                                    </p>
                                </a>
                            @endforeach
                        @else
                            <a
                                class="dropdown-item notify-item text-center">
                                <p class="notify-details">Nothing found</p>
                            </a>
                        @endif
                    </div>
                    <!-- All-->
                    <a href="{{ route('notification.index') }}" class="dropdown-item notify-all">
                        View All
                    </a>

                </div>
            </li>


            <li class="list-inline-item dropdown notification-list nav-user">
                <a class="nav-link dropdown-toggle arrow-none waves-effect" data-toggle="dropdown" href="#"
                   role="button"
                   aria-haspopup="false" aria-expanded="false">
                    <span class="d-inline-block ml-1" style="font-size: 19px">
                        <i class="mdi mdi-chevron-down"></i>
                        <i class="mdi mdi-account"></i>
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated profile-dropdown" style="width: auto">
                    <span class="dropdown-item">
                        <i class="dripicons-mail text-muted"></i>
                        {{ auth()->user()->email }}
                    </span>
                    <a class="dropdown-item" href="{{route('profile')}}"><i class="dripicons-user text-muted"></i>
                        Profile</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ route('user.logout') }}"><i class="dripicons-exit text-muted"></i>
                        Logout</a>
                </div>
            </li>

        </ul>
    </nav>
    <marquee direction="right"  class="navbar-custom .marquee" style="background-color: #ffffff59; padding: 3.5px" scrolldelay="300" onmouseover="this.stop();" onmouseout="this.start();">
        <ul class="list-inline d-inline-block menu-left mb-0 nav-user">
            <li class="ml-4 btn btn-warning btn-sm" style="font-size: 13px;">
                <span>CTR: </span>
                <span>${{ $price_currency['ctr'] }}</span>
            </li>
            <li class="ml-4 btn btn-danger btn-sm" style="font-size: 13px;">
                <span>BTT: </span>
                <span>${{ $price_currency['btt'] }}</span>
            </li>
        </ul>
    </marquee>

</div>
<!-- Top Bar End -->