routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use IEXBase\TronAPI\Tron;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|اینجا وقتیی که کاربر رفته باشه داخل پنلش میتونه دسترسی داشته باشه
روت های لاگین داخل فایل web.php موجود میباشد
*/
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
Route::post('users/{user}/block-unblock','UsersController@block_unblock')->name('users.block_unblock');
Route::resource('users','UsersController');
Route::get('users/{user}/login-panel', 'UsersController@login_panel')->name('users.login-panel');
Route::resource('invest_shares','Invest_SharesController');
Route::post('invest_shares/profits','Invest_SharesController@inviter_profit_store')->name('invest_shares.inviter_profit.store');
Route::post('invest_shares/cancel-invest','Invest_SharesController@cancel_invest')->name('invest_shares.cancel_invest');
Route::resource('ctr','CtrController')->only(['index','store']);
Route::post('ctr/profits','CtrController@inviter_profit_store')->name('ctr.inviter_profit.store');

Route::get('settings','SettingsController@general')->name('settings.general');
Route::get('settings/withdraws','SettingsController@withdraw')->name('settings.withdraws');
Route::post('settings','SettingsController@update')->name('settings.general.store');
Route::post('settings/currency','SettingsController@currency_update')->name('settings.currency.store');
Route::get('/profile', 'ProfileController@profile')->name('profile');
Route::put('/profile/{user}', 'ProfileController@update_profile')->name('profile.update');
Route::put('/change-password/{user}', 'ProfileController@change_pass')->name('change-password');
Route::get('reports','ReportController@index')->name('reports.index');
Route::resource('notifications','NotificationController');
Route::get('get-user','NotificationController@users')->name('notifications.get_user');
Route::get('get-amount','UsersController@get_amount')->name('get_amount');
Route::post('users/change_wallet','UsersController@change_wallet')->name('users.change_wallet');
Route::post('settings/message','SettingsController@message')->name('settings.message.update');
Route::get('ticket', "TicketsController@index")->name('ticket.index');
Route::get('ticket/create', "TicketsController@create")->name('ticket.create');
Route::get('ticket/{code}/show', "TicketsController@show")->name('ticket.show');
Route::post('ticket/close', "TicketsController@close")->name('ticket.close');
Route::post('ticket/{code}/update', "TicketsController@update")->name('ticket.update');

routes/web.php
<?php

use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use IEXBase\TronAPI\Tron;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', "App\Http\Controllers\User\HomeController@home");
Route::get('/file/{guard}/{id}/{file}',
    function ($guard, $id, $file) {
        $path = storage_path('app/public/tickets/' . $guard . '/' . $id . '/' . $file);
        if (!File::exists($path)) {
            abort(404);
        }
        $file = File::get($path);
        $type = File::mimeType($path);
        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);
        return $response;
    })->name('file.ticket.view');

Route::post('convert-to-parameter-save', function (\Illuminate\Http\Request $request) {
    $model = \App\Models\TransactionTron::find($request->id);
    $model->ethers_data = $request->address;
    $model->save();
    return 1;
})->name('convert-to-parameter-save');

// روت هایی برای ورود ادمین
Route::middleware('guest.admin')
    ->prefix('admin')
    ->name('admin.')
    ->namespace('App\Http\Controllers\Admin\Auth')
    ->group(function () {
        Route::get('login', 'LoginController@loginForm')->name('login.form');
        Route::post('login', 'LoginController@login')->name('login');
    });

Route::middleware('guest')->namespace('App\Http\Controllers\User\Auth')->group(function () {
    Route::get('register', 'RegisterController@register')->name('register.form');
    Route::post('register/store', 'RegisterController@store')->name('register.store');
    Route::get('register/{code?}', 'RegisterController@show_registration_form')->name('register');
    Route::get('email/verify/{token}', 'RegisterController@verifyEmail')->name('register.verify.email');
    Route::get('forget/password', 'ForgetPasswordController@forget')->name('forget.form');
    Route::post('forget/send-email', 'ForgetPasswordController@sendEmail')->name('forget.send-email');
    Route::get('forget/verify/{token}', 'ForgetPasswordController@verifyToken')->name('forget.verify-token');
    Route::post('forget/new-password', 'ForgetPasswordController@newPassword')->name('forget.new-password');
    Route::get('login', 'LoginController@loginForm')->name('login.form');
    Route::post('login/user', 'LoginController@login')->name('login.login');
    Route::get('login/step', 'LoginController@login_step_form')->name('login.step.form');
    Route::post('login/step/user', 'LoginController@login_step')->name('login.step')->middleware('2fa.login');
});

// روت های مربوط به کاربر که داخل پنل کاربری لاگین شده
Route::middleware('auth')->namespace('App\Http\Controllers\User')->group(function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('user.dashboard');
    Route::get('settings', 'SettingController@general')->name('user.settings');

    Route::get('invest/cancel/{invest_shares}', 'Invest_SharesController@cancel')->name('user.invest.cancel');
    Route::get('invest/add-to-share/{invest_shares}', 'Invest_SharesController@add_to_share')->name('user.invest.add_to_share');
    Route::get('invest/{invest_shares}/logs', 'Invest_SharesController@logs')->name('user.invest.logs');
    Route::get('shares/{invest_shares}/logs', 'Invest_SharesController@logs')->name('user.shares.logs');
    Route::resource('invest', 'Invest_SharesController', ['as' => 'user']);
    Route::resource('shares', 'Invest_SharesController', ['as' => 'user']);
    Route::get('buy-ctr', 'AssetsController@buy_ctr_view')->name('user.buy-ctr');
    Route::post('buy-ctr', 'AssetsController@buy_ctr_store')->name('user.buy-ctr.store');

    Route::post('register_authenticator', 'SettingController@register_authenticator')->name('user.register_authenticator');
    Route::post('deactivate_authenticator', 'SettingController@deactivate_authenticator')->name('user.deactivate_authenticator');
    Route::post('login_2fa', 'SettingController@login_2fa')->name('user.login_2fa');
    Route::get('logout', 'Auth\LoginController@logout')->name('user.logout');
    Route::get('notifications', 'NotificationController@index')->name('notification.index');
    Route::get('notification/{id}', 'NotificationController@show')->name('notification.show');

    Route::post('assets/{asset_unit}/price-on-usdt', 'AssetsController@price_on_usdt')->name('assets.price_on_usdt');
    Route::post('assets/{asset_unit}/convert-to-usdt', 'AssetsController@convert_to_usdt')->name('assets.convert_to_usdt');

    Route::get('assets', 'AssetsController@index')->name('assets');
    Route::post('assets/get-address-wallet', 'AssetsController@getAddressWallet')->name('assets.get-address-wallet');
    Route::post('assets/get-amount-wallet', 'AssetsController@getAmountWallet')->name('assets.get-amount-wallet');
    Route::post('assets/withdrawal-fee', 'AssetsController@WithdrawalFee')->name('assets.wallet.withdrawal-fee');
    Route::post('assets/withdraw', 'AssetsController@withdraw')->name('assets.withdraw.store')->middleware(['auth', '2fa']);
    Route::post('assets/security-withdraw', 'AssetsController@security_withdraw')->name('assets.withdraw.security');
    Route::post('withdraw', 'AssetsController@withdraw')->name('withdraw.store')->middleware(['auth', '2fa']);
    Route::get('withdraw-report', 'TransactionController@withdraw_report_form')->name('withdraw-report');
    Route::get('/profile', 'DashboardController@profile')->name('profile');
    Route::put('/profile/{user}', 'DashboardController@update_profile')->name('profile.update');
    Route::put('/change-password/{user}', 'DashboardController@change_pass')->name('change-password');
    Route::get('ticket', "TicketController@index")->name('ticket.index');
    Route::get('ticket/create', "TicketController@create")->name('ticket.create');
    Route::get('ticket/{code}/show', "TicketController@show")->name('ticket.show');
    Route::post('ticket/store', "TicketController@store")->name('ticket.store');
    Route::post('ticket/{code}/update', "TicketController@update")->name('ticket.update');
});

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Asset;
use App\Models\BaseData;
use App\Models\Finance_transaction;
use App\Models\Invest_Shares;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{
    // نشان دادن لیست کاربران
    public function index(Request $request)
    {
        $users = User::query();
        $request->code ? $users->where('code', 'like', '%' . $request->code . '%') : '';
        $request->email ? $users->where('email', 'like', '%' . $request->email . '%') : '';
        $request->first_name ? $users->where('first_name', 'like', '%' . $request->first_name . '%') : '';
        $request->last_name ? $users->where('last_name', 'like', '%' . $request->last_name . '%') : '';
        $request->status ? $users->where('status', $request->status) : '';
        if ($request->has('export')) {
            $data = $users->get();
            switch ($request->export) {
                case 'excel':
                    return exportExcel($this->dataToExport($data));
                    break;
                case 'pdf':
                    return exportPdf($this->dataToExport($data));
                    break;
            }
            return exportExcel($this->dataToExport($data));
        }
        $users = $users->paginate(10);
        return view('admin.users.index', compact('users'));
    }

    // نشان دادن اطلاعات یک کاربر
    public function show(User $user)
    {
        $invest_shares = $user
            ->invest_shares()
            ->join('base_data', function ($join) {
                $join
                    ->on('invest_shares.type', '=', 'base_data.type')
                    ->where(function ($query) {
                        $query
                            ->where(function ($query) {
                                $query
                                    ->where('initial_value', '>=', DB::raw('base_data.extra_field1'))
                                    ->where('initial_value', '<', DB::raw('base_data.extra_field2'));
                            })
                            ->orWhere(function ($query) {
                                $query
                                    ->where('invest_shares.initial_value', '>=', DB::raw('base_data.extra_field1'))
                                    ->where('base_data.extra_field2', '-1');
                            });
                    });
            })
            ->get(['invest_shares.id as id', 'invest_shares.type', 'initial_value', 'invest_shares.status', 'profit', 'extra_field3 as percent', 'invest_shares.created_at', 'invest_shares.updated_at']);
        return view('admin.users.show', compact('user', 'invest_shares'));
    }

    // ویرایش اطلاعات کاربری
    public function update(User $user, Request $request)
    {
        if (!$request->ajax())
            return redirect()->back();
        try {
            if (is_null($request->password) || !$request->password)
                unset($request['password']);
            else
                $request['password'] = Hash::make($request->password);
            $user->update($request->except(['id', 'code', 'google2fa_secret', 'email_verified_at', 'verification', 'time_verification', 'reject_reason', 'remember_token', 'deleted_at', 'created_at', 'updated_at']));
            return response()->json(['status' => 100, 'msg' => 'تغییرات با موفقیت اعمال شد']);
        } catch (\Exception $exception) {
            dd($exception);
            return response()->json(['status' => 500, 'msg' => 'مشکلی پیش آمده است لطفا مجدد تلاش کنید']);
        }
    }

    // بلاک و آنبلاک کردن کاربر
    public function block_unblock(User $user, Request $request)
    {
        if (!$request->ajax())
            return redirect()->back();

        try {
            if ($user->status == 2) {
                $user->status = 0;
                $user->reject_reason = '';
                $msg = 'کاربر مورد نظر با موفقیت آنبلاک شد!

                 وضعیت پنل کاربر به غیرفعال تغییر کرد.';
            } else {
                $user->status = 2;
                $user->reject_reason = $request->reject_reason;
                $msg = 'کاربر مورد نظر با موفقیت بلاک شد!';
            }
            $user->save();
            return response()->json(['status' => 100, 'msg' => $msg]);
        } catch (\Exception $exception) {
            return response()->json(['status' => 500, 'msg' => 'مشکلی پیش آمده است لطفا مجدد تلاش کنید']);
        }
    }

    // لاگین کردن با کاربر داخل پنل
    public function login_panel(User $user)
    {
        Auth::logout();
        Auth::login($user);
        return redirect('/dashboard');
    }

    public function get_amount(Request $request)
    {
        try {
            $amount = Asset::query()
                ->select('id', 'amount')
                ->where('user_id', $request['user_id'])
                ->where('unit', $request['unit'])
                ->get();

            return response()->json($amount);
        } catch (\Exception $exception) {
            return response()->json(['error' => 'error']);
        }
    }

    public function change_wallet(Request $request)
    {
        $request->validate([
            'unit' => 'required',
            'amount' => 'required|numeric',
            'transact_type' => 'required',
        ]);

        try {
            $asset = Asset::where('user_id', $request->user_id)
                ->where('unit', $request->unit)->first();
            if ($request['amount'] > $asset->amount && $request['transact_type'] == 'decrease') {
                return response()->json(['status' => 500, 'msg' => 'مقدار کاهش بیشتر از موجودی کاربر می باشد.']);
            }
            if ($request['transact_type'] == 'increase') {
                $type = 2;
                $description = 'wallet amount increased by admin (' . $request['unit'] . ')';
                $base_data = BaseData::where('type', 'transactions')->where('extra_field1', 10)->first()->id;
                $amount = $asset->amount + $request['amount'];
            } else {
                $type = 1;
                $description = 'wallet amount decreased by admin (' . $request['unit'] . ')';
                $base_data = BaseData::where('type', 'transactions')->where('extra_field1', 11)->first()->id;
                $amount = $asset->amount - $request['amount'];
            }

            $asset->update([
                'amount' => $amount,
            ]);

            Finance_transaction::create([
                'financeable_id' => $asset->id,
                'financeable_type' => 'App\Models\Asset',
                'tracking_code' => '',
                'user_id' => $request['user_id'],
                'transact_type' => $base_data,
                'amount' => $request['amount'],
                'type' => $type,
                'extra_field1' => '',
                'description' => $description,
            ])->save();

            return response()->json(['status' => 100, 'msg' => 'عملیات با موفقیت انجام شد.']);
        } catch (\Exception $exception) {
            return response()->json(['status' => 500, 'msg' => 'خطایی رخ داده است لطفا بعدا امتحان کنید.']);
        }

    }


    protected function dataToExport($data)
    {
        $array = [];
        $i = 1;
        foreach ($data as $item) {
            array_push($array, [
                '#' => $i,
                'نام و نام خانوادگی' => $item->name,
                'ایمیل' => $item->email,
                'کد' => $item->code,
                'وضعیت پنل' => ($item->status == 1) ? 'فعال' : 'غیرفعال',
                'تاریخ ثبت نام' => Carbon::parse($item->created_at)->format('Y/m/d'),
            ]);
            $i++;
        }
        return $array;
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\BaseData;
use App\Models\Invest_Shares;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function dashboard()
    {
        $result=[];
        $result['count_notification']=countNotificationNotView();
        $invests= auth()->user()->invest()->active()->get();
        $share= auth()->user()->invest()->active()->first();
        $cancel_invest = parameter_cancel_invest();
        return view('user.dashboard',compact('result','invests','cancel_invest','share'));
    }

    public function home()
    {
        return view('home');
    }
}

resources/views/user/dashboard.blade.php
@extends('templates.user.master_page')
@section('title_browser')
    dashboard
@endsection
@section('style')
    <style>
        .list-feature {
            padding-left: 0px;
        }

        .list-feature li {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            list-style: none;
            padding-top: 12px;
        }
        .swal-modal .swal-text {
            text-align: center;
        }
    </style>
@endsection
@section('content')
    <!-- start Share -->
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="row align-items-center">
                    <div class="col-md-8">
                        <h4 class="page-title m-0">Share</h4>
                    </div>
                    <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end page-title-box -->
        </div>
    </div>

    <div class="row">
        @if ($share)
            <div class="col-xl-4 col-md-6 position-relative">
                <div class="card bg-white mini-stat text-dark">
                    <div class="p-3 mini-stat-desc">
                        <div class="clearfix text-info">
                            <h6 class="mt-0 float-left text-dark-50">Initial value</h6>
                            <h4 class="mb-3 mt-0 float-right">{{ $share->initial_value }} <sub
                                    style="font-size: .5em;"> USDT</sub></h4>
                        </div>
                        <div>
                            <ul class="list-feature">
                                <li>
                                    <span class="text-dark">Your profit</span>
                                    <span
                                        class="text-success font-weight-bold"> +{{ $share->profit }} btt </span>
                                </li>
                                <li>
                                    <span class="text-dark">Created at</span>
                                    <span class="text-secondary">{{ $share->created_at }}</span>
                                </li>
                                <li>
                                    <span class="text-dark">Last update</span>
                                    <span class="text-secondary">{{ $share->updated_at }}</span>
                                </li>
                            </ul>

                        </div>

                    </div>
                    <div class="btn-group btn-group-justified col-12 px-0 row mx-auto">
                        <a href="{{ route('user.shares.logs',$share) }}"
                           class="font-14 m-0 btn btn-info col-12">Logs</a>
                    </div>
                </div>
            </div>
        @else
            <div class="col-12 alert alert-primary">
                you dont have any shares
                <a href="{{ route('user.shares.create') }}" class="btn btn-primary btn-sm mx-2">Buy new shares</a>
            </div>
        @endif
    </div>
    <!--## end Share -->


    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="row align-items-center">
                    <div class="col-md-8">
                        <h4 class="page-title m-0">Invest</h4>
                    </div>
                    <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end page-title-box -->
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        @if (count($invests) > 0)
            @foreach($invests as $key=>$item)
                <div class="col-xl-4 col-md-6 position-relative">
                    <div class="card bg-white mini-stat text-dark">
                        <div class="p-3 mini-stat-desc">
                            <div class="clearfix text-primary">
                                <h6 class="mt-0 float-left text-dark-50">Initial value</h6>
                                <h4 class="mb-3 mt-0 float-right">{{ $item->initial_value }} <sub
                                        style="font-size: .5em;"> USDT</sub></h4>
                            </div>
                            <div>
                                <ul class="list-feature">
                                    <li>
                                        <span class="text-dark">Your profit</span>
                                        <span
                                            class="text-success font-weight-bold"> +{{ $item->profit }} ctr </span>
                                    </li>
                                    <li>
                                        <span class="text-dark">Created at</span>
                                        <span class="text-secondary">{{ $item->created_at }}</span>
                                    </li>
                                    <li>
                                        <span class="text-dark">Last update</span>
                                        <span class="text-secondary">{{ $item->updated_at }}</span>
                                    </li>
                                    <li>
                                        <span>Cancellation percentage</span>
                                        <span class="text-secondary">{{ intval($cancel_invest['percent'])  }}%</span>
                                    </li>
                                    @if ($cancel_invest['date'] !== true && $cancel_invest['date'] != false)
                                        <li>
                                            <span>Next Date Cancellation <sub> (without damage)</sub></span>
                                            <span class="text-secondary">{{ $cancel_invest['date']  }}</span>
                                        </li>
                                    @endif
                                </ul>

                            </div>

                        </div>
                        <div class="btn-group btn-group-justified col-12 px-0 row mx-auto">
                            <a href="{{ route('user.invest.add_to_share',['invest_shares'=>$item->id]) }}"
                               class="font-14 m-0 btn btn-success col-sm-4 confirm-box" data-val="{{ $item->initial_value }}">Add To Share</a>
                            <a href="{{ route('user.invest.cancel',['invest_shares'=>$item->id]) }}"
                               class="font-14 m-0 btn btn-danger col-sm-4 confirm-box" data-val="{{ $item->initial_value }}">Cancel</a>
                            <a href="{{ route('user.invest.logs',$item) }}"
                               class="font-14 m-0 btn btn-info col-sm-4">Logs</a>
                        </div>
                    </div>
                </div>
            @endforeach
        @else
            <div class="col-12 alert alert-primary">
                you dont have any invests
                <a href="{{ route('user.invest.create') }}" class="btn btn-primary btn-sm mx-2">Buy new invest</a>
            </div>
        @endif
    </div>
    <!-- end row -->
@endsection
@section('script')
    <script>
        $(".confirm-box").click(function (event) {
            event.preventDefault();
            let confirm_box = $(this);
            let cancellation_fee= '{{ $cancel_invest['date'] === true?0:$cancel_invest['percent'] }}';
            let val= $(this).data('val');
            let cancellation_price= ((100-cancellation_fee)/100)/val;
            let text= 'It is not possible to return after cancellation Or Add To Share! \n\r';
            text += `percent of cancellation: ${cancellation_fee}% \n\r`
            text += `total price of cancellation: ${cancellation_price.toFixed(4)} usdt \n\r`;
            swal({
                title: "Are You Sure?",
                text: text,
                icon: "warning",
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete == true) {
                    window.location.replace(confirm_box.attr('href'));
                }
            });
        })
    </script>
@endsection